In [72]:
import numpy as np
arr=np.arange(0,11)


In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr*arr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
arr=arr +100

In [86]:
arr=np.array([float(i)for i in arr])
arr

array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.])

In [89]:
arr**20

array([1.00000000e+40, 1.22019004e+40, 1.48594740e+40, 1.80611123e+40,
       2.19112314e+40, 2.65329771e+40, 3.20713547e+40, 3.86968446e+40,
       4.66095714e+40, 5.60441077e+40, 6.72749995e+40])